name: SpeedBuildersPractice
version: 1.0
main: it.andrea.speedbuilders.Main
depend: [HolographicDisplays]
commands:
  map:
    description: Gestione arene
  practice:
    description: Entra in gioco
  p:
    description: Alias per practice
  lobby:
    description: Torna alla lobby
    aliases: [ l ]
  fly:
    description: Attiva o disattiva il volo
  dj:
    description: Attiva o disattiva il doppio salto
  savemineplex:
    description: Salva manualmente una build di Mineplex
  scanall:
    description: Scansiona tutte le build di Mineplex nel raggio