name: SpeedBuildersPractice
version: 1.0
main: it.andrea.speedbuilders.Main
commands:
  map:
    description: Gestione plot SpeedBuilders
    usage: /map <create|load|edit|rename|delete|confirm|setup|setlobby|setpractice>
  practice:
    description: Teletrasporta al mondo di allenamento
    aliases: [p]
  lobby:
    description: Torna alla lobby principale